#!/usr/bin/env node

require('dotenv').config();

const repl = require('repl').start('> ');
const GitHubApi = require('github');
const github = new GitHubApi();

github.authenticate({
  type: 'oauth',
  token: process.env.GITHUB_TOKEN
});

repl.context.github = github;
