#!/usr/bin/env node

const repl = require('repl').start('> ');
let GitHubApi = require('github');
let github = new GitHubApi();

github.authenticate({
  type: 'oauth',
  token: process.env.GITHUB_TOKEN
});

repl.context.github = github;
