#!/bin/bash

# Exit if a command returns a non-zero code
set -e

# Store the versions
VERSION=$(git describe --tags --match "v[0-9]*" --abbrev=0 | sed 's/^v//')
HEAD=$(git rev-parse HEAD)

_CREATE_TAGS_OPTION=''

# Generate docs
npm run doc

# Checkout the website into the tmp directory
[ -d tmp/website ] || {
  REPO=https://github.com/probot/probot.github.io

  # If GH_TOKEN environment variable is present, use that to push.
  if [[ -n "$GH_TOKEN" ]]; then
    REPO=${REPO/https:\/\//https://${GH_TOKEN}@}
  fi

  mkdir -p tmp
  git clone $REPO tmp/website
}

# Update the website checkout
cd tmp/website
git pull origin master

# Allow tagging later on when $VERSION from `probot` repo doesn't exist on `probot.github.io` repo
if [ -z "$(git tag --list "$VERSION")" ]; then
  _CREATE_TAGS_OPTION="--tags"
fi

# Delete previously generated docs for this version
rm -rf "api/$VERSION"

# Copy over the new docs
mv ../../out "api/$VERSION"

# Update the /api/latest link to point to this version
ln -sfn "$VERSION" api/latest

# Update the submodule
git submodule update --init
cd _submodules/probot
git fetch
git checkout "$HEAD"
cd ../..

# Commit and publish
git add .
git commit -m "Update docs for v$VERSION"
if [ -n "$_CREATE_TAGS_OPTION" ]; then
  git tag "v$VERSION"
fi
git push "$_CREATE_TAGS_OPTION" origin master
